### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by dinaw** [deokpyo/fnsz_extension#4]
Logged on first thing this morning and it wasn't loading. Attached screenshot of the console. 
<img width="1439" alt="screen shot 2017-10-12 at 10 00 30 am" src="https://user-images.githubusercontent.com/19753698/31503106-5c0a6c10-af34-11e7-8834-e5c2285f858d.png">

**Comment by deokpyo** [comment]
Just uploaded a new version. Check in about an hour. Re-download the [extension](https://chrome.google.com/webstore/detail/funsize/hphdebhbkjmiilpenemcmmfbbafidamn) when you see the version updated to 0.4.6.

**Comment by deokpyo** [comment]
Fixed!
