### ISSUE TITLE
Chrome Extension doesn't laod

### ISSUE THREAD

**Issue by dinaw** [deokpyo/fnsz_extension#5]
<img width="1440" alt="screen shot 2017-10-16 at 10 30 21 am" src="https://user-images.githubusercontent.com/19753698/31620582-395b0414-b25d-11e7-93c5-de218bbc40cd.png">

**Comment by deokpyo** [comment]
Fixed! This was an issue with not saving the "refresh_token" to re-authenticate the user after the token has expired.
