### ISSUE TITLE
Chrome Extension showing days that have passed

### ISSUE THREAD

**Issue by dinaw** [deokpyo/fnsz_extension#6]
I reinstalled the chrome extension and it works.. kinda.. it's showing Oct 13th when it's the 16th rn. Hmm?  <img width="1412" alt="screen shot 2017-10-16 at 4 01 18 pm" src="https://user-images.githubusercontent.com/19753698/31635107-53cdb61a-b28b-11e7-8177-c2c75fb3e432.png">

**Comment by dinaw** [comment]
Only thing I think that that caused this is that we rescheduled that Funsize All Hands meeting from Friday 13th to Monday 16th? And maybe it didn't register that? Who knows.

**Comment by deokpyo** [comment]
Fixed! The extension will now filter the events based on current date and no longer display past events.
