### ISSUE TITLE
BG Color not changing

### ISSUE THREAD

**Issue by dinaw** [deokpyo/fnsz_extension#7]
<img width="1433" alt="screen shot 2017-11-09 at 10 02 29 am" src="https://user-images.githubusercontent.com/19753698/32615795-4a08a32a-c536-11e7-81a8-1156aab23ce3.png">

BG colors don't change without a refresh when the time changes.

**Comment by deokpyo** [comment]
There was an issue with setIntervals function to watch for current time to update background and time block colors.

This issue has been fixed.
